---
# tasks file for devstack
- hosts: localhost
  connection: local
  tasks:
    # Make sure all servers allow ssh input.
    - name: add ssh ingress rule
      os_security_group_rule:
        state: present
        security_group: default
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
    - name: create a volume to hold the development files
      os_volume:
        state: present
        wait: yes
        size: 200
        display_name: '{{devstack_server_name}}_files'
    - name: launch devstack
      os_server:
        name: '{{devstack_server_name}}'
        state: present
        wait: yes
        auto_ip: yes
        # FIXME: Switch to 16.04
        image: Ubuntu-16.04
        flavor_ram: 8192
        key_name: '{{devstack_key_name}}'
        network: public
        volumes:
          - '{{devstack_server_name}}_files'
      register: devstack_server
    - debug:
        var: devstack_server.server.public_v4
    - name: add the server to our ansible inventory
      add_host: hostname="{{ devstack_server.server.public_v4 }}"
                groups=devstack
                ansible_ssh_private_key_file="{{devstack_ssh_private_key_file}}"
                ansible_ssh_user=ubuntu

# Wait for the server to finish booting and become accessible.
- hosts: devstack
  gather_facts: no
  tasks:
    - name: Wait for instance to finish booting
      connection: local
      wait_for:
        host="{{ansible_ssh_host|default(inventory_hostname)}}"
        search_regex=OpenSSH
        port=22
        delay=30
        timeout=600
    - name: Try to login to the instance
      raw: "/bin/ls"
      retries: 5
      delay: 10
      ignore_errors: true

# Make the new Ubuntu 16.04 compatible with Ansible.
- hosts: devstack
  gather_facts: no
  tasks:
    - name: "Install python2.7 since Ubuntu 16.04 doesn't ship it"
      raw: "sudo apt-get update -y && sudo apt-get install -y python2.7 aptitude"
      retries: 5
      delay: 10

# Configure the /opt filesystem. This has to be separate from the
# previous step and next step for ordering.
- hosts: devstack
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python2.7

  # Create a filesystem on the attached volume. /dev/vdb
  tasks:
    - name: Create /opt filesystem
      filesystem: fstype=ext4 dev=/dev/vdb
      become: true
      become_user: root
      become_method: sudo
    - name: Mount /opt filesystem
      mount: name=/opt src=/dev/vdb fstype=ext4 state=mounted
      become: true
      become_user: root
      become_method: sudo
